name: textlint format
on: [pull_request, workflow_dispatch]
jobs:
  textlint:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4.1
        with:
          node-version: 22.x
      - name: Run textlint
        # textlint の終了コードを強制0にする
        run: npx textlint --fix ${FILES} | true
        shell: bash {0}
        env:
          FILES: articles/*.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'style(textlint): auto fix'
