name: textlint format
on: 
  - pull_request
  - workflow_dispatch

jobs:
  textlint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install pnpm dependencies
        run: pnpm install
      
      - name: Run textlint
        run: npx textlint --format ${FILES}
        env:
          FILES: articles/**/*.md
